append_unmatched: true
nav:
  - 首页: index.md
  - 开发版概述:
      - 开发版简介: introduction.md
      - 基本概念: concepts.md
      - 功能与限制: limitations.md
  - 快速开始:
      - 快速开始概述: get-started/index.md
      - 使用 Docker Compose 部署: get-started/deploy.md
      - 连接并完成首次查询: get-started/first-query.md
      - 示例数据: get-started/dataset.md
  - 服务器管理:
      - 配置管理:
          - Docker Compose 配置说明: server-admin/configurations/docker-compose.md
  - 社区与共创:
      - 参与文档编写: contributing.md
      - 通过 AI 使用文档: ai.md
